<?php

return [
    'profile' => 'Профіль',
    'dashboard' => 'Панель управління',
    'add' => 'Додати',
    'create' => 'Створити',
    'edit' => 'Редагувати',
    'show' => 'Переглянути',
    'save' => 'Зберегти',
    'saved' => 'Збережено',
    'saved_error' => 'Помилка',
    'filters' => 'Фільтри',
    'search' => 'Пошук',
    'reset' => 'Скинути',
    'total' => 'Загалом',
    'deleted' => 'Видалено',
    'delete' => 'Видалити',
    'deleting' => 'Видалення',
    'download' => 'Завантажити',
    'export' => 'Експорт',
    'import' => 'Імпорт',
    'cancel' => 'Скасувати',
    'confirm' => 'Підтвердити',
    'close' => 'Закрити',
    'confirm_message' => 'Ви впевнені?',
    'back' => 'Назад',
    'more' => 'Ще',
    'all_sections' => 'Всі розділи',
    'file' => 'Файл',
    'loading' => 'Завантаження ...',
    'notfound' => 'Записи не знайдено',
    'collapse_menu' => 'Згорнути меню',
    '404' => 'Х’юстон, у нас проблема. Сторінку не знайдено',
    'copied' => 'Скопійовано!',
    'notifications' => [
        'title' => 'Сповіщення',
        'mark_as_read_all' => 'Позначити всі як прочитані',
        'mark_as_read' => 'Позначити як прочитане',
    ],
    'login' => [
        'title' => 'Ласкаво просимо до :moonshine_title!',
        'description' => 'Будь ласка, увійдіть до свого облікового запису',
        'authorization' => 'Авторизація',
        'remember_me' => 'Запам’ятати мене',
        'login' => 'Увійти',
        'logout' => 'Вийти',
        'username' => 'Ім’я користувача',
        'email' => 'E-mail',
        'password' => 'Пароль',
    ],
    'resource' => [
        'system' => 'Система',
        'role' => 'Ролі',
        'name' => 'Ім’я',
        'email' => 'E-mail',
        'password' => 'Пароль',
        'repeat_password' => 'Повторіть пароль',
        'avatar' => 'Аватар',
        'created_at' => 'Створено',
        'admins_title' => 'Адміністратори',
        'role_title' => 'Ролі',
        'role_name' => 'Назва',

        'main_information' => 'Основна інформація',
        'change_password' => 'Змінити пароль',

        'queued' => 'У черзі',

        'export' => [
            'exported' => 'Файл експортовано',
        ],

        'import' => [
            'imported' => 'Імпортовано',
            'file_required' => 'Файл обов’язковий',
            'extension_not_supported' => 'Розширення файлу не підтримується',
        ],
    ],
    'choices' => [
        'no_results' => 'Результатів не знайдено',
        'no_choices' => 'Немає варіантів для вибору',
        'item_select' => 'Натисніть для вибору',
        'unique_item' => 'Можна додати лише унікальні значення',
        'custom_add_item' => 'Можна додати лише значення, що відповідають певним умовам',
        'add_item' => 'Натисніть Enter, щоб додати ":value"',
        'max_item' => 'Можна додати лише :count значень',
        'remove_item' => 'Видалити елемент',
    ],
];